version: '3.8'

services:
  zap:
    image: zaproxy/zap-stable
    command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true
    ports:
      - "8080:8080"
    networks:
      - strikehound-net

  strikehound:
    build: .
    depends_on:
      - zap
    volumes:
      - ./output:/app/output
      - ./config.yaml:/app/config.yaml
    networks:
      - strikehound-net

networks:
  strikehound-net:
    driver: bridge
